server:
  name: tinyUrl
  port: 9069

# 日志文件目录及debug级别
log:
  dir: ./logs
  console: true
  level: debug

# redis 相关配置
redis:
  host: 127.0.0.1:6379
  password:
  poolsize:

# mongodb 相关配置
mongo:
  host: 127.0.0.1:27017
  user: yangping
  password: 123456
  poolsize: 4096
  dbName: tiny_url

# 转换相关配置
convert:
  # 进制转换字符串
  binaryStr: 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
  # 长链接过期时间
  longUrlExpire: 60
  # 短链接过期时间
  tinyUrlExpire: 60
jwt:
  jwtSecret: 123
  jwtExpireTime: 20
  issuer: YaPi